-- THIS FILE HAS BEEN MOVED TO sql-scripts/crm-migration.sql
-- CRM Database Migration Script
-- This script should be run against the BuildX database
-- Usage: psql -h 127.0.0.1 -p 5432 -U postgres -d BuildX -f ../sql-scripts/crm-migration.sql
