-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "address" TEXT,
ADD COLUMN     "alternateMobile" TEXT,
ADD COLUMN     "assignedTo" TEXT,
ADD COLUMN     "attachments" TEXT[],
ADD COLUMN     "baySpacing" DOUBLE PRECISION,
ADD COLUMN     "convertedDate" TIMESTAMP(3),
ADD COLUMN     "craneCapacity" DOUBLE PRECISION,
ADD COLUMN     "craneRequired" BOOLEAN DEFAULT false,
ADD COLUMN     "createdBy" TEXT,
ADD COLUMN     "customFields" JSONB,
ADD COLUMN     "customerId" TEXT,
ADD COLUMN     "customerNotes" TEXT,
ADD COLUMN     "gstNumber" TEXT,
ADD COLUMN     "height" DOUBLE PRECISION,
ADD COLUMN     "insulationRequired" BOOLEAN DEFAULT false,
ADD COLUMN     "insulationThickness" DOUBLE PRECISION,
ADD COLUMN     "insulationType" TEXT,
ADD COLUMN     "length" DOUBLE PRECISION,
ADD COLUMN     "mapCoordinates" TEXT,
ADD COLUMN     "materialPreference" TEXT,
ADD COLUMN     "mezzanine" BOOLEAN DEFAULT false,
ADD COLUMN     "mezzanineArea" DOUBLE PRECISION,
ADD COLUMN     "mezzanineLoad" DOUBLE PRECISION,
ADD COLUMN     "pincode" TEXT,
ADD COLUMN     "roofType" TEXT,
ADD COLUMN     "score" INTEGER,
ADD COLUMN     "siteAddress" TEXT,
ADD COLUMN     "siteLocation" TEXT,
ADD COLUMN     "soilNotes" TEXT,
ADD COLUMN     "specialRequirement" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "updatedBy" TEXT,
ADD COLUMN     "wallType" TEXT,
ADD COLUMN     "width" DOUBLE PRECISION,
ALTER COLUMN "city" DROP NOT NULL;

-- CreateIndex
CREATE INDEX "Lead_assignedToId_idx" ON "Lead"("assignedToId");
