export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DOMAIN_RULE_VIOLATION: 'DOMAIN_RULE_VIOLATION',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  OPTIMISTIC_LOCK: 'OPTIMISTIC_LOCK',
  IDEMPOTENCY_REUSE: 'IDEMPOTENCY_REUSE',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
